"""Workers : commit, fork, review, issue."""
import os
import random
import time
from datetime import datetime, timezone

from .hawkes import simulate_hawkes, DEFAULT_PARAMS
from .fly_art import generate_fly, render_commit_panel
from .github_api import gh, create_file, get_default_branch
from .state import load as load_state, save as save_state

REPO = os.environ.get("TARGET_REPO", "glowku/the-fly-autonomous-worker")

MESSAGES = [
    "fly: bzzz into the void",
    "fly: wing flap optimization",
    "fly: landing trajectory fix",
    "fly: refract light on compound eye",
    "fly: escape swatter (edge case)",
    "fly: spawn new worker in parallel",
    "fly: refactor wing beat loop",
    "fly: reduce drag coefficient",
    "fly: sync with hive mind",
    "fly: handle tailwind gracefully",
]

STATES = ["FOCUS", "REVIEW", "DEBUG", "SHIP", "IDLE"]


def _metrics(t_min, batch, state=None):
    """Métriques DORA simulées pour l'affichage du panneau."""
    return {
        "state": state or random.choice(STATES),
        "latent": random.randint(80, 420),
        "lead_time": f"{random.randint(1, 4)}h{random.randint(0, 59):02d}",
        "ttfr": f"{random.randint(3, 45)}m",
        "batch": batch,
        "t": t_min,
    }


def _utcnow():
    """UTC aware, remplace datetime.utcnow() déprécié en 3.12."""
    return datetime.now(timezone.utc)


def run_commit_batch(n=20, seed=None):
    """Génère n commits Hawkes-datés, chacun avec une mouche ASCII."""
    events = simulate_hawkes(**DEFAULT_PARAMS, T_minutes=60, seed=seed or int(time.time()))
    events = events[:n]

    if not events:
        print("[commit] aucun événement généré (Hawkes vide)", flush=True)
        return []

    state = load_state()
    branch = get_default_branch(REPO)
    results = []

    for i, t_min in enumerate(events):
        msg = random.choice(MESSAGES)
        fly = generate_fly(seed=int(time.time() * 1000) + i)
        panel = render_commit_panel(fly, _metrics(t_min, i + 1))

        # Path unique : microsecondes + index pour éviter les collisions
        ts = _utcnow()
        path = f"flies/{ts.strftime('%Y%m%d')}/fly_{int(ts.timestamp() * 1e6)}_{i}.txt"

        try:
            create_file(
                REPO,
                path,
                panel,
                f"{msg}\n\n[fly-worker batch={i + 1}/{len(events)} t={t_min:.1f}min]",
                branch=branch,
            )
            results.append({"status": "ok", "path": path, "msg": msg})
            print(f"[commit {i + 1}/{len(events)}] {msg} @ t={t_min:.1f}min", flush=True)
        except Exception as e:
            print(f"[commit {i + 1}] erreur: {e}", flush=True)
            results.append({"status": "error", "reason": str(e)})

    ok = sum(1 for r in results if r["status"] == "ok")
    state["total_commits"] = state.get("total_commits", 0) + ok
    try:
        save_state(state)
    except Exception as e:
        print(f"[commit] save_state a échoué : {e}", flush=True)

    return results


def run_fork_batch(n=3):
    """Fork + branche + commit + PR vers le repo principal."""
    owner, name = REPO.split("/")
    results = []
    state = load_state()

    for i in range(n):
        try:
            fork = gh("POST", f"/repos/{owner}/{name}/forks")
            fork_owner = fork["owner"]["login"]
            time.sleep(2)  # laisse le fork se propager

            ref = gh("GET", f"/repos/{fork_owner}/{name}/git/ref/heads/main")
            base_sha = ref["object"]["sha"]
            branch = f"fly-{int(time.time())}-{i}"

            gh(
                "POST",
                f"/repos/{fork_owner}/{name}/git/refs",
                json={"ref": f"refs/heads/{branch}", "sha": base_sha},
            )

            fly = generate_fly(seed=int(time.time()) + i)
            path = f"contributions/fly_{branch}.txt"
            create_file(
                f"{fork_owner}/{name}",
                path,
                fly,
                f"fly: contribution from worker #{i}",
                branch=branch,
            )

            pr = gh(
                "POST",
                f"/repos/{owner}/{name}/pulls",
                json={
                    "title": f"🪰 fly contribution {branch}",
                    "head": f"{fork_owner}:{branch}",
                    "base": "main",
                    "body": f"```\n{fly}\n```\n\nAuto-generated by the-fly-worker.",
                },
            )
            results.append({"status": "ok", "pr": pr["number"], "branch": branch})
            print(f"[fork {i + 1}/{n}] PR #{pr['number']} créée", flush=True)
            time.sleep(3)
        except Exception as e:
            print(f"[fork {i + 1}] erreur: {e}", flush=True)
            results.append({"status": "error", "reason": str(e)})

    ok = sum(1 for r in results if r["status"] == "ok")
    state["total_prs"] = state.get("total_prs", 0) + ok
    try:
        save_state(state)
    except Exception as e:
        print(f"[fork] save_state a échoué : {e}", flush=True)

    return results


def run_review_batch(n=3):
    """Poste des reviews sur les PRs ouvertes."""
    owner, name = REPO.split("/")
    results = []
    state = load_state()

    try:
        prs = gh("GET", f"/repos/{owner}/{name}/pulls?state=open&per_page=20")
    except Exception as e:
        print(f"[review] impossible de lister les PRs: {e}", flush=True)
        return [{"status": "error", "reason": str(e)}]

    for i, pr in enumerate(prs[:n]):
        pr_number = pr["number"]
        try:
            fly = generate_fly(seed=pr_number)
            review = (
                "## 🪰 Auto-review by fly-worker\n\n"
                "**Metrics**\n"
                f"- Lead time estimé : {random.randint(1, 4)}h{random.randint(0, 59):02d}\n"
                f"- Time to first response : {random.randint(3, 45)}m\n"
                "- State : REVIEW\n\n"
                "**Observations**\n"
                "- Structure du diff cohérente.\n"
                "- Complexité cyclomatique acceptable.\n"
                "- Suggestion : ajouter un test sur le cas limite `state == IDLE`.\n\n"
                "```\n"
                f"{fly}\n"
                "```\n"
            )
            gh(
                "POST",
                f"/repos/{owner}/{name}/pulls/{pr_number}/reviews",
                json={"body": review, "event": "COMMENT"},
            )
            results.append({"status": "ok", "pr": pr_number})
            print(f"[review {i + 1}/{n}] PR #{pr_number} review postée", flush=True)
        except Exception as e:
            print(f"[review {i + 1}] erreur: {e}", flush=True)
            results.append({"status": "error", "reason": str(e)})

    ok = sum(1 for r in results if r["status"] == "ok")
    state["total_reviews"] = state.get("total_reviews", 0) + ok
    try:
        save_state(state)
    except Exception as e:
        print(f"[review] save_state a échoué : {e}", flush=True)

    return results


def run_issue_batch(n=3):
    """Crée des issues ASCII mouche sur le repo principal."""
    owner, name = REPO.split("/")
    results = []
    state = load_state()

    for i in range(n):
        try:
            fly = generate_fly(seed=int(time.time()) + i)
            msg = random.choice(MESSAGES)
            issue = gh(
                "POST",
                f"/repos/{owner}/{name}/issues",
                json={
                    "title": f"🪰 {msg}",
                    "body": (
                        f"```\n{fly}\n```\n\n"
                        f"Auto-filed by fly-worker · state={random.choice(STATES)}"
                    ),
                    "labels": ["fly", "auto"],
                },
            )
            results.append({"status": "ok", "issue": issue["number"]})
            print(f"[issue {i + 1}/{n}] #{issue['number']} créée", flush=True)
            time.sleep(1)
        except Exception as e:
            print(f"[issue {i + 1}] erreur: {e}", flush=True)
            results.append({"status": "error", "reason": str(e)})

    state["total_issues"] = state.get("total_issues", 0) + sum(
        1 for r in results if r["status"] == "ok"
    )
    try:
        save_state(state)
    except Exception as e:
        print(f"[issue] save_state a échoué : {e}", flush=True)

    return results